project: <WANDB_PROJECT>
entity: <WANDB_ENTITY>
program: scOT/train.py
method: grid
metric:
  name: "eval/loss"
  goal: minimize
command:
  - "HDF5_USE_FILE_LOCKING=FALSE"
  - "accelerate" 
  - "launch"
  - ${program}
 