project: <WANDB_PROJECT>
entity: <WANDB_ENTITY>
program: scOT/train.py
method: grid
metric:
  name: "eval/loss"
  goal: minimize
command:
  - "HDF5_USE_FILE_LOCKING=FALSE"
  - "accelerate" 
  - "launch"
  - ${program}
  - "--disable_tqdm"
  - "--json-config"
  - "--finetune_from"
  - "camlab-ethz/Poseidon-B"
  - "--replace_embedding_recovery"
  - "--config"
  - ${args_json}
parameters:
  dataset:
    value: "wave.Layer"
  num_trajectories:
    values:
      - 1
      - 2
      - 4
      - 8
      - 16
      